### ISSUE TITLE
Engine rpm stuck at 5800

### ISSUE THREAD

**Issue by SPIROS80** [r9r-dev/fs2020-vl3-rotax915#10]
For some reason , I cannot control engine rpm through the prop controller (by changing pitch) as I did and it stays at 5800 (according to the EFIS) all the time. Even when I throttle back to idle power which is not normal at all. I also have the Working Title GX mod (dev-4).

**Comment by ArashHosseini** [comment]
@SPIROS80 what do you mean with by changing pitch? Pitch has obviously nothing to do with rpm and prop. I think you are looking for this one to change the rpm:

![Screenshot from 2021-04-15 13-29-27](https://user-images.githubusercontent.com/9273754/114862292-a0c56380-9dee-11eb-97a5-348da4836f2e.png)

**Comment by SPIROS80** [comment]
I understand what you are showing me exactly. I use the same governor from Woodcomp in real life, in my Sting RG. I change the rpm of the 914 from there. The rpm remains at the set point as the governor controls the pitch of the three blades. In manual mode I can change the pitch from full fine to full coarse. The instrument at that time was not working and I could not change rpm. With the later mod releases , it is now working. But do not forget , we control (in real life) rpm by changing the pitch of the propeller blades. Finer pitch gives us higher rpm and coarser pitch gives us lower rpm for given throttle setting.

**Comment by ArashHosseini** [comment]
@SPIROS80 i see, your post is from December, 

> But do not forget , we control (in real life) rpm by changing the pitch of the propeller blades. Finer pitch gives us higher rpm and coarser pitch gives us lower rpm for given throttle setting.

yes, familiar to me. Thanks for sharing this. And i think you can close the ticket.
