### ISSUE TITLE
Blank PFD and MFD

### ISSUE THREAD

**Issue by snookerfly** [r9r-dev/fs2020-vl3-rotax915#16]
I just downloaded and installed the latest version of the VL-3 (v0.31) and WorkingTitle GX (v0.1.0-dev8). Unfortunately I only have blank PFD and MFD (with or without installed WorkingTitle packages).
Any hints on what I might be missing?

![Microsoft Flight Simulator Screenshot 2021 07 14 - 13 39 00 19 Thumbnail](https://user-images.githubusercontent.com/16756846/125616795-21a4f87e-5748-4562-b915-62951421ee67.png)

**Comment by a-peter** [comment]
Have you tried using the (meanwhile) most recent v0.1.0-dev10 of the WorkingTitle GX?

**Comment by snookerfly** [comment]
seems to work with the latest release
