### ISSUE TITLE
Instant take off

### ISSUE THREAD

**Issue by r9r-dev** [r9r-dev/fs2020-vl3-rotax915#2]
After landing and coming to a complete stop, when the plane is turned on again, it takes off instantly.

**Comment by r9r-dev** [comment]
Version 0.3 should fix this issue. Needs confirmation :)

**Comment by GotGravel** [comment]
Yes seems to be fixed with the changes in the power_scalar vs thrust_scalar balance.

**Comment by r9r-dev** [comment]
Okay, closing this issue according to tests
