### ISSUE TITLE
Fuel flow and manifold pressure is inacurate

### ISSUE THREAD

**Issue by asudakov** [r9r-dev/fs2020-vl3-rotax915#3]
Rotax 915iS tops out at 205KTAS burning 9-9.7 gph at 35 manifold pressure at ~5500rpm. I am getting over 12 gph fuel flow. 

Furthermore, Rotaxes are pretty efficient at lower power settings. At 65% load R915iS should make 4800 rpm at 29 in-Hq manifold and sip just 4.7gph of fuel making 146KTAS. At 55% and 4300rpm and 28 in-Hq manifold fuel flow is 3.7gph at 125KIAS.

VL-3 is advertised as being able to make New York to Miami flight non-stop.

I couldn't figure out what parameters in engines.cfg control fuel flow to power to RPM to manifold pressure ratios. Any ideas?

Also here is [a link](https://www.rotax-owner.com/en/support-topmenu/engine-manuals) to other Rotax manuals with performance charts better than in 915 manual

**Comment by asudakov** [comment]
Played with fuel_flow_scalar and it has no effect on fuel flow. Tested values from 0.02 to 1.02 - no effect on fuel flow but a side effect that at fuel_flow_scalar = 1.02 the plane would not stop on a runway with cut throttle and breaks applied :)

fuel_metering_type also has no effect. 
Neither
min_cruise_rpm = 4300
max_cruise_rpm = 5500
max_indicated_rpm = 5800

I am still getting from 3 gph @ 11 manifold (cut throttle) to 12 gph @ 36 manifold.

**Comment by r9r-dev** [comment]
Not at home atm but there is a `manifold_efficiency_table` setting. Current value is `0:0.25, 1:0.97`.

**Comment by CodenameJack** [comment]
Lowering or increasing SFC affects consumption.

**Comment by r9r-dev** [comment]
Problem solved for a long time now :) Closing the issue.
