### ISSUE TITLE
two improvements in lights

### ISSUE THREAD

**Issue by argento-ar** [r9r-dev/fs2020-vl3-rotax915#6]
Proposed Changes:
On file **systems.cfg**
from
lightdef.4 = Type:5#...#LocalRotation:0,0,0#...
to
lightdef.4 = Type:5#...#LocalRotation:**-10**,0,0#...

result, it angles the landing light a little upwards (10 degrees), so you can actually see whats is in front and below your aircraft, not only below.

Bugfix, on **systems.cfg**
from
lightdef.5 = Type:2#....#EffectFile:LIGHT_ASOBO_StrobeSimple#...
to
lightdef.5 = Type:2#...#EffectFile:**LIGHT_ASOBO_StrobeTop**#...

Is the tail strobe light, on the default VL3 is bad, on the external view, you can only see it on the front 180degrees of front part of the aircraft, not on from behind, that change makes the top tail strobe to a omnidirectional light, like in reality

**Comment by TalonHawke** [comment]
Thanks for this, it's been added!
