### ISSUE TITLE
systems.cfg error

### ISSUE THREAD

**Issue by argento-ar** [r9r-dev/fs2020-vl3-rotax915#7]
Hey Guys!
Talon implemented my sugested changes to systems.cfg but, he inadvertently made an error, just checked 

Line 10: lightdef.4 = Type:5#Index:0#LocalPosition:4.92,-0.7,-0.75#LocalRotation:10,0,0
old value: LocalRotation:0,0,0 i suggested LocalRotation:-10,0,0 (MINUS 10,zero,zero)

With the actual values , the landing light , points even more below the aircraft :)

**Comment by GotGravel** [comment]
Thanks! Corrected .... it's now -10.
